[template]
src = "brickftp-boomi.tmpl"
dest = "/home/etl/.ssh/brickftp"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 994
gid = 991
mode = "0600"

keys = [
    "/config/*",
    "/config"
]
