[template]
src = "bugzilla.py.tmpl"
dest = "/opt/etl/bugzilla/config.py"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
