[template]
src = "geoip.tmpl"
dest = "/etc/GeoIP.conf"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]

reload_cmd = "/bin/geoipupdate -v; /bin/geoipupdate3 -v"
