[template]
src = "snapshot.tmpl"
dest = "/usr/local/bin/nubis-etl-snapshot"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0755"

keys = [
    "/config/*",
    "/config"
]
