[template]
src = "snippets-stats.tmpl"
dest = "/usr/local/virtualenvs/snippets-stats/bin/config.py"
prefix = "/%%PROJECT%%-%%ENVIRONMENT%%/%%ENVIRONMENT%%"

uid = 0
gid = 0
mode = "0644"

keys = [
    "/config/*",
    "/config"
]
